version: '3.9'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  backend:
    build: .
    restart: always
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
volumes:
  postgres:
